[build]
  command = "bun install && bun run build --filter=@ordo/dashboard"
  publish = "apps/dashboard/.output/public"
  functions = "apps/dashboard/.output/server"

[build.environment]
  NODE_VERSION = "20"

# Enable Netlify Functions
[functions]
  directory = "apps/dashboard/.output/server"

# Handle all routes through the server function
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

